CodeReview/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'CodeReview.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^review-results/', include('ReviewResults.urls')),
)

ReviewResults/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import home, get_or_create_group, review_step_2, review_step_3, load_step_3, save_step_3, load_step_4, save_step_4


urlpatterns = patterns('',
    url(r'^$', home, name='home'),
    url(r'^get-or-create-group/$', get_or_create_group, name="get_or_create_group"),
    url(r'^review-step-2/$', review_step_2, name="review_step_2"),
    url(r'^review-step-3/$', review_step_3, name="review_step_3"),
    url(r'^load-step-3-data/$', load_step_3, name="load_step_3"),
    url(r'^save-step-3/$', save_step_3, name="save_step_3"),
    url(r'^load-step-4/$', load_step_4, name="load_step_4"),
    url(r'^save-step-4/$', save_step_4, name="save_step_4"),
)

ReviewResults/models.py
from django.db import models


class review_rule_master(models.Model):
    rule_master_object = models.CharField(max_length = 25)
    rule_master_desc = models.CharField(max_length = 100)

    def __unicode__(self):
        return self.rule_master_desc

class review_rule(models.Model):
    rule_master = models.ForeignKey(review_rule_master)
    rule_object = models.CharField(max_length = 25)
    rule_name = models.CharField(max_length = 100)
    rule_desc = models.CharField(max_length = 100)
    rule_error = models.CharField(max_length = 100)
    rule_custom_flag = models.CharField(max_length = 1, default = 'N')

    def __unicode__(self):
        return self.rule_name

class review_rule_operation(models.Model):
    rule = models.ForeignKey(review_rule)
    rule_operation = models.CharField(max_length = 50)

    def __unicode__(self):
        return self.rule_operation

class review_rule_property(models.Model):
    rule = models.ForeignKey(review_rule)
    rule_property = models.CharField(max_length = 50)

    def __unicode__(self):
        return self.rule_property

class review_rule_category(models.Model):
    rule_category = models.CharField(max_length = 25)

    def __unicode__(self):
        return self.rule_category

class review_rule_priority(models.Model):
    rule_priority = models.CharField(max_length = 25)

    def __unicode__(self):
        return self.rule_priority

class review_rule_group_name(models.Model):
    rule_group_name = models.CharField(max_length=25)

    def __unicode__(self):
        return self.rule_group_name

class review_rule_group(models.Model):
    rule_group_name = models.ForeignKey(review_rule_group_name)
    rule = models.ForeignKey(review_rule)
    rule_desc = models.CharField(max_length = 100)
    rule_category = models.CharField(max_length = 25)
    rule_priority = models.CharField(max_length = 25)
    rule_operation = models.CharField(max_length = 50, null = True)
    rule_property = models.CharField(max_length = 50, null = True)

    def __unicode__(self):
        return "%s %s" % (self.rule_group_name.rule_group_name, self.rule.rule_name)

ReviewResults/views.py
from django.shortcuts import render, render_to_response
from .models import review_rule_group_name, review_rule_master, review_rule_group, review_rule_operation, review_rule_property, review_rule, review_rule_priority, review_rule_category
from django.template.context import RequestContext
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
import json

# Create your views here.
def home(request):
    _rule_group = review_rule_group_name.objects.all()
    return render(request, "ReviewResults/home.html", {"rule_group": _rule_group})


def get_or_create_group(request):
    if request.is_ajax():
        if request.method == "POST":
            response_data = {}
            rule_group_name = request.POST.get("rule_group_name")
            if rule_group_name == "":
                response_data["status"] = "not allowed"
                response_data["reason"] = "Empty Value"
                return HttpResponse(json.dumps(response_data), content_type="application/json")
            try:
                group = review_rule_group_name.objects.get(rule_group_name=rule_group_name)
                group_id = group.id
            except:
                group = review_rule_group_name(rule_group_name=rule_group_name)
                group.save()
                group_id = group.id
            response_data["status"] = "success"
            response_data["id"] = group_id
            return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        raise PermissionDenied


def review_step_2(request):
    if request.is_ajax():
        if request.method == "GET":
            id = request.GET.get("id")
            group = review_rule_group_name.objects.get(id=id)
            rule_group = review_rule_group.objects.filter(rule_group_name=group)
            all_rules = review_rule.objects.all()
            selected_rules = []
            for rules in rule_group:
                if rules.rule not in selected_rules:
                    selected_rules.append(rules.rule)

            template = "ReviewResults/step_2.html"
            data = {
                "group": group,
                "rule_master": rule_master,
                "selected_rules": selected_rules,
                "rule_group": rule_group
            }
            return render_to_response(template, data, context_instance=RequestContext(request))
    else:
        raise PermissionDenied


def review_step_3(request):
    if request.is_ajax():
        response_data = {}
        if request.method == "POST":
            group_name_id = request.POST.get("group_name_id")
            rule_masters_arr = request.POST.getlist("rule_masters[]")
            rule_group_name = review_rule_group_name.objects.get(id=group_name_id)
            #rg = review_rule_group.objects.filter(rule_group_name=rule_group_name)
            if u"" not in rule_masters_arr:
                # convert post data to int
                s = []
                for y in rule_masters_arr:
                    s.append(int(y))
                rule_masters_arr = s
                for rule_master_id in rule_masters_arr:
                    rm = review_rule_master.objects.get(id=rule_master_id)
                    rules = rm.review_rule_set.all()
                    for rule in rules:
                        exists = review_rule_group.objects.filter(rule_group_name=rule_group_name, rule=rule)
                        if len(exists) == 0:
                            rg = review_rule_group(rule_group_name=rule_group_name, rule=rule)
                            rg.save()

                current_master = []
                rg = review_rule_group.objects.filter(rule_group_name=rule_group_name)
                for rule in rg:
                    if rule.rule.rule_master.id not in current_master:
                        current_master.append(rule.rule.rule_master.id)

                if rule_masters_arr != current_master:
                    for id in current_master:
                        if id not in rule_masters_arr:
                            rm = review_rule_master.objects.get(id=id)
                            rules = review_rule.objects.filter(rule_master=rm)
                            rg = review_rule_group.objects.filter(rule_group_name=rule_group_name, rule=rules)
                            rg.delete()


            # existing_rule_group = review_rule_group.objects.filter(rule_group_name=rule_group_name)
                response_data["status"] = "success"
            # response_data["rule"] = existing_rule_group
            else:
                try:
                    rg = review_rule_group.objects.filter(rule_group_name=rule_group_name)
                    rg.delete()
                    response["status"] = "Master Rule deleted"
                except:
                    response_data["status"] = "failed"
            return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        raise PermissionDenied


def load_step_3(request):
    if request.is_ajax():
        if request.method == "GET":
            group_name_id = request.GET.get("id")
            group_name = review_rule_group_name.objects.get(id=group_name_id)
            rule_group_rule = review_rule_group.objects.filter(rule_group_name=group_name)
            # print "tes"
            template = "ReviewResults/step_3.html"
            data = {"rule_groups": rule_group_rule, "group_name": group_name}
        return render_to_response(template, data, context_instance=RequestContext(request))
    else:
        raise PermissionDenied


def save_step_3(request):
    if request.is_ajax():
        response_data = {}
        if request.method == "POST":
            group_name_id = request.POST.get("group_name_id")
            operations = request.POST.getlist("operations[]")
            properties = request.POST.getlist("properties[]")
            rule_ids = request.POST.getlist("rule_id[]")
            group_name = review_rule_group_name.objects.get(id=group_name_id)
            for x in range(0, len(rule_ids)):
                rule = review_rule.objects.get(id=rule_ids[x])
                if operations[x] == u'':
                    operation = ""
                else:
                    try:
                        id = int(operations[x])
                        operation = review_rule_operation.objects.get(id=id)
                        operation = operation.rule_operation
                    except:
                        operation = operations[x]
                if properties[x] == u'':
                    propert = ""
                else:
                    try:
                        id = int(properties[x])
                        propert = review_rule_property.objects.get(id=id, rule=rule)
                        propert = propert.rule_property
                    except:
                        propert = properties[x]
                rule_group = review_rule_group.objects.get(rule_group_name=group_name, rule=rule)
                rule_group.rule_operation = operation
                rule_group.rule_property = propert
                rule_group.save()

            response_data["status"] = "success"
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        raise PermissionDenied


def load_step_4(request):
    if request.is_ajax():
        if request.method == "GET":
            id = request.GET.get("id")
            rg_name = review_rule_group_name.objects.get(id=id)
            rg  = review_rule_group.objects.filter(rule_group_name=rg_name)
            categories = review_rule_category.objects.all()
            priorities = review_rule_priority.objects.all()
            template = "ReviewResults/step_4.html"
            data = {
                "rule_groups": rg,
                "priorities": priorities,
                "categories": categories,
                "group_name": rg_name,
            }
            return render_to_response(template, data, context_instance=RequestContext(request))
    else:
        raise PermissionDenied


def save_step_4(request):
    if request.is_ajax():
        response_data = {}
        if request.method == "POST":
            id = request.POST.get("rule_group_name")
            group_name = review_rule_group_name.objects.get(id=int(id))
            rule_group = review_rule_group.objects.filter(rule_group_name=group_name)
            categories = request.POST.getlist("rule_categories[]")
            priorities = request.POST.getlist("rule_priorities[]")
            rule_ids = request.POST.getlist("rule_ids[]")


            for x in range(0, len(rule_ids)):
                rule = review_rule.objects.get(id=int(rule_ids[x]))
                # print rule
                try:
                    group = review_rule_group.objects.get(rule_group_name=group_name, rule=rule)
                    # print group

                    if categories[x] == u"":
                        rule_category = ""
                    else:
                        category_id = int(categories[x])
                        category = review_rule_category.objects.get(id=category_id)
                        rule_category = category.rule_category

                    if priorities[x] != u"":
                        priority_id = int(priorities[x])
                        priority = review_rule_priority.objects.get(id=priority_id)
                        rule_priority = priority.rule_priority
                    else:
                        rule_priority = ""


                    group.rule_category = rule_category
                    group.rule_priority = rule_priority
                    group.rule_desc = rule.rule_desc + " " + group.rule_operation + " " + group.rule_property
                    group.save()
                    response_data["status"] = "success"
                except:
                    response_data["status"] = "failed"
            print response_data

ReviewResults/templates/ReviewResults/home.html
{% extends 'base.html' %}
{% block content %}

    <div class="wizard" data-initialize="wizard" id="group_profile">
        <ul class="steps">
            <li data-step="1" class="active">
                <span class="badge">1</span>Step 1<span class="chevron"></span>
            </li>
            <li data-step="2">
                <span class="badge">2</span>Step 2<span class="chevron"></span>
            </li>
            <li data-step="3">
                <span class="badge">3</span>Step 3<span class="chevron"></span>
            </li>
            <li data-step="4">
                <span class="badge">4</span>Step 4<span class="chevron"></span>
            </li>
        </ul>
        <div class="step-content">
            <div class="step-pane active sample-pane alert" data-step="1">
                <form class="form-horizontal">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-md-2">
                    <label class="control-label" for="rule_profile">Rule Profile</label>
                    </div>
                    <div class="col-md-6">
                        <input class="form-control" placeholder="Choose Available or Type New" type="text" list="list" id="rule_profile">
                        <datalist id="list">
                            {% for group in rule_group %}
                                <option value="{{ group.rule_group_name }}"></option>
                            {% endfor %}
                        </datalist>
                        <!-- <p class="note"><strong>Note:</strong> works in Chrome, Firefox, Opera and IE10.</p> -->
                    </form>

                    </div>
                    <div class="text-right">
                        <br />
                        <br />
                        <button class="btn btn-primary" id="step1_next" type="button">Next</button>
                    </div>
                </div>

            </div> <!-- EOF step 1 -->

            <!-- step 2 content -->
            <div class="step-pane sample-pane alert" data-step="2">
                <div id="step2" class="table-responsive"></div>
            </div>

            <!-- EOF step 2 -->
            <div class="step-pane sample-pane alert" data-step="3">
                <div id="step3" class="table-responsive"></div>
            </div>

            <div class="step-pane sample-pane alert" data-step="4">
                <div id="step4" class="table-responsive"></div>
            </div>

        </div>
    </div>
{% endblock %}
{% block additional_script %}
<script type="text/javascript">
    $('#step1_next').click(function() {
        var group_name = $("#rule_profile").val();
        var csrf_token = $('input[name=csrfmiddlewaretoken').val();
        var data = {
            "rule_group_name": group_name,
            "csrfmiddlewaretoken": csrf_token
        };
        console.log(data);
        $.ajax({
            type: "POST",
            url: "/review-results/get-or-create-group/",
            data: data,
            async: false,
            success: function(data) {
                console.log(data);
                if(data.status == "success") {
                    var id = data.id;

                    $('#step2').html('&nbsp;').load('{% url "review_step_2" %}?id=' + id);
                    $('#group_profile').wizard('next');
                } else if (data.status == "not allowed") {
                    alert(data.reason);
                    $("#rule_profile").addClass("form-control-error");
                    return false;
                }
            }
        });
    })
    </script>
{% endblock %}

ReviewResults/templates/ReviewResults/step_2.html
{% block content %}
    <h3>{{ title }}</h3>
<form id="rule_master" action="#" method="post">
{% csrf_token %}
<input type="hidden" id="group_name_id" value="{{ group.id }}" />


<select multiple id="rule_master" name="masters[]">
    {% for master in rule_master %}
        {% if master in selected_master %}

            <option value="{{ master.id }}" selected>{{ master.rule_master_desc }}</option>

        {% else %}
           <optgroup label="Hello">
            <option value="{{ master.id }}">{{ master.rule_master_desc }}</option>
            </optgroup>
        {% endif %}
  {% endfor %}
</select>

<br />
<br />


</form>
<br />
<br />
<div class="text-right">
    <button type="button" class="btn btn-default" id="prev_step">Previous</button>
    <button type="button" class="btn btn-primary" id="update_rule_group">Next</button>
</div>

<script>

$("#rule_master").multiSelect({
    selectableHeader: "<input type='text' class='form-control' autocomplete='off'>",
  selectionHeader: "<input type='text' class='search-input form-control' autocomplete='off'>",
  afterInit: function(ms){
    var that = this,
        $selectableSearch = that.$selectableUl.prev(),
        $selectionSearch = that.$selectionUl.prev(),
        selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
        selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

    that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
    .on('keydown', function(e){
      if (e.which === 40){
        that.$selectableUl.focus();
        return false;
      }
    });

    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
    .on('keydown', function(e){
      if (e.which == 40){
        that.$selectionUl.focus();
        return false;
      }
    });
  },
  afterSelect: function(){
    this.qs1.cache();
    this.qs2.cache();
  },
  afterDeselect: function(){
    this.qs1.cache();
    this.qs2.cache();
  }
});

function save_step2() {
    var group_name_id = $("#group_name_id").val();
    var rule_masters = $('[name="masters[]"]').val();
    var csrf_token = $('input[name=csrfmiddlewaretoken').val();
    var data = {'action': "update_step2", 'group_name_id': group_name_id, "rule_masters[]": rule_masters, "csrfmiddlewaretoken": csrf_token};
    console.log(data);

    if (rule_masters == null) {
        alert("Please select at least one rule master");
        $('[name="duallistbox_item[]_helper2"]').addClass("form-control-error");
        return false;
    }


    $.ajax({
        "type": "POST",
        "url": "/review-results/review-step-3/",
        "data": data,
        "async": false,
        "success": function(data) {
            if (data.status == 'success') {
                $('#step3').html('&nbsp;').load('{% url "load_step_3" %}?id=' + group_name_id);
                $('#group_profile').wizard('next');
                //console.log(data);
            }
        }
    });
}

var rule_master = $('select[name="duallistbox_item[]"]').bootstrapDualListbox();
    $("#demoform").submit(function() {
      alert($('[name="duallistbox_item[]"]').val());
      return false;
    });

$('#update_rule_group').click(function() {
    //alert($('[name="duallistbox_item[]"]').val());
    save_step2();

});

$("#prev_step").click(function() {
    $('#group_profile').wizard('previous');
})

</script>
{% endblock %}

ReviewResults/templates/ReviewResults/step_3.html
<div id="{{ rule_groups.rule_master.id }}">
<table class="table table-striped" id="step3_table">
<input type="hidden" name="group_name_id" value="{{ group_name.id }}" id="group_name_id"/>
{% csrf_token %}
{% for rule in rule_groups %}
    <tr>
        <td>
            {{ rule.rule.rule_desc }}<input type="hidden" name="rule_id[]"  value="{{ rule.rule.id }}" />
        </td>
        {% if rule.rule.rule_custom_flag == "N" %}
            <td><input type="hidden" id="operations[]" value="" name="operations[]"/>&nbsp;</td><td><input type="hidden" name="properties[]" />&nbsp;</td>

        {% else %}
            <td>
                {% if rule.rule.review_rule_operation_set.count > 0 %}
                <select name="operations[]" class="form-control" >
                    <option value=""> -- Select Value -- </option>
                    {% for operation in rule.rule.review_rule_operation_set.all %}
                        <option value="{{ operation.id }}" {% if operation.rule_operation == rule.rule_operation %} selected="selected" {% endif %}>{{ operation.rule_operation }}</option>
                    {% endfor %}
                </select>
                {% else %}
                    <input type="hidden" value="" name="operations[]">
                {% endif %}
            </td>
            <td>
                {% if rule.rule.review_rule_property_set.count > 0 %}
                    <select name="properties[]" class="form-control">
                                                    <option value=""> -- Select Value -- </option>
                        {% for property in rule.rule.review_rule_property_set.all %}
                            <option value="{{ property.id }}" {% if property.rule_property == rule.rule_property %} selected="selected" {% endif %}>{{ property.rule_property }}</option>
                        {% endfor %}
                    </select>
                {% else %}
                    <input type="text" name="properties[]" placeholder="enter the value" class="form-control" {% if rule.rule_property %}value="{{ rule.rule_property }}" {% endif %}/>
                {% endif %}

            </td>
        {% endif %}
    </tr>

{% endfor %}
</table>

<div class="text-right">
    <button class="btn btn-default" id="btn_prev_step2" type="button">Previous</button> &nbsp;
    <button class="btn btn-primary" id="btn_next_step4">
        Next
    </button>
</div>
</div>

<script>
var group_name_id = $("#group_name_id").val();
function save_step3() {
    
    var _properties = $("[name='properties[]']");
    
    var _operations = $("[name='operations[]']");
    var csrf_token = $('input[name=csrfmiddlewaretoken').val();
    var _rule_id = $("[name='rule_id[]']");

    var rule_id = [];
    var operations = [];
    var properties = [];
    

    for (var i = 0; i < _rule_id.length; i++) {
        rule_id.push(_rule_id[i].value);
        operations.push(_operations[i].value);
        properties.push(_properties[i].value);
    }

    var data = {
        "group_name_id": group_name_id,
        "csrfmiddlewaretoken": csrf_token,
        "operations[]": operations,
        "properties[]": properties,
        "rule_id[]": rule_id
    }
    $.ajax({
        "type": "POST",
        "url": "/review-results/save-step-3/",
        "data": data,
        'async': false,
        "success": function(data) {
            console.log(data.status);
            if(data.status != "success") {
                alert("Somethig wrong");
                return false;
            }
        }
    });
}

function validate_input3() {
    var input_text = $("#step3_table").find("input[type!='hidden']");
    var input_select = $("#step3_table").find("select[type!='hidden']");
    
    var lanjut = true;
    var input = []
    
    for (var i = 0; i < input_text.length; i++) { 
        if ( input_text[i].value == "" ) { 
            lanjut = false;
            $(input_text[i]).addClass("form-control-error");
            input.push(input_text[i]);
        } 
    }
    
    for (var i = 0; i < input_select.length; i++) {
        if ( input_select[i].value == "" ) {
            $(input_select[i]).addClass("form-control-error");
            input.push(input_select[i]);
        }
    }
    
    return input;
}


$("#btn_next_step4").click(function(e) {
    e.preventDefault();
    var validasi = validate_input3();
   
    if(validasi.length >  0) {
        alert("Some input cannot be empty");
        console.log(validasi.value);
    } else {
        var t = save_step3();
        $('#step4').html('&nbsp;').load('{% url "load_step_4" %}?id=' + group_name_id);
        $('#group_profile').wizard('next');        
    }
    
});

$("#btn_prev_step2").click(function(e) {
    e.preventDefault()
    save_step3();
    $('#group_profile').wizard('previous');
});


</script>

ReviewResults/templates/ReviewResults/step_4.html
<table class="table table-striped" id="step4_table">
    <input type="hidden" value="{{ group_name.id }}" id="group_name" />
     {% for group in rule_groups %}
        <tr>
            {% csrf_token %}
            <td>{{ group.rule.rule_desc }}<input type="hidden" value="{{ group.rule.id }}" name="rule_ids[]"/></td>
            <td>{{ group.rule_operation}}</td>
            <td>{{ group.rule_property }}</td>
            <td>
                <select name="priorities[]" class="form-control">
                    <option value=""> -- Select Value -- </option>
                    {% for priority in priorities %}
                        <option value="{{ priority.id }}" {% if group.rule_priority == priority.rule_priority %} selected="selected" {% endif %}>{{ priority.rule_priority }}</option>
                    {% endfor %}
                </select>
            </td>
            <td>
                <select class="form-control" name="categories[]">
                    <option value=""> -- Select Value -- </option>
                    {% for cat in categories %}
                        <option value="{{ cat.id }}" {% if group.rule_category == cat.rule_category %} selected="selected" {% endif %}>{{ cat.rule_category }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
     {% endfor %}
</table>
<div class="text-right">
    <button type="button" class="btn btn-default" id="to_step3">Previous</button> &nbsp;
    <button class="btn btn-primary" id="save_all_step" type="button">Save</button>
</div>

<script>


function save4(group_name_id) {
    var _rule_ids = $("[name='rule_ids[]']");
    var _rule_priorities = $("[name='priorities[]']");
    var _rule_categories = $("[name='categories[]']");
    var csrf_token = $('input[name=csrfmiddlewaretoken').val();

    var rule_ids = [];
    var rule_priorities = [];
    var rule_categories = [];

    for (var i = 0; i < _rule_ids.length; i++) {
        rule_ids.push(_rule_ids[i].value);
        rule_priorities.push(_rule_priorities[i].value);
        rule_categories.push(_rule_categories[i].value);
    }

    var result = "";

    var data = {
        "csrfmiddlewaretoken": csrf_token,
        "rule_group_name": group_name_id,
        "rule_priorities[]": rule_priorities,
        "rule_categories[]": rule_categories,
        "rule_ids[]": rule_ids
    }

    // console.log(data);

    $.ajax({
        "type": "POST",
        "url": "/review-results/save-step-4/",
        "data": data,
        'async': false,
        "success": function(data) {
            //console.log(data);
            if (data.status == "success") {
                //console.log(data.status);
                result = data;
//                 save_event(data);
                //return(data);
            }
            //result = data;
        }
    });
    //console.log(result);
    return result
}

function validate_input4() {
    var input_text = $("#step4_table").find("input[type!='hidden']");
    var input_select = $("#step4_table").find("select[type!='hidden']");

    var lanjut = true;
    var input = []

    for (var i = 0; i < input_text.length; i++) {
        if ( input_text[i].value == "" ) {
            lanjut = false;
            $(input_text[i]).addClass("form-control-error");
            input.push(input_text[i]);
        }
    }

    for (var i = 0; i < input_select.length; i++) {
        if ( input_select[i].value == "" ) {
            $(input_select[i]).addClass("form-control-error");
            input.push(input_select[i]);
        }
    }

    return input;
}


    $("#save_all_step").click(function() {
        var group_name_id = $("#group_name_id").val();
        var validasi = validate_input4();

        if (validasi.length > 0) {
            alert("Please Select Value");
        } else {
            var t = save4(group_name_id);
            if (t.status == "success") {
                alert("data Saved");
            }
        }

    });

$("#to_step3").click(function(e) {
    e.preventDefault()
    var group_name_id = $("#group_name_id").val();
    var s = save4(group_name_id);
    console.log(s.status);
    $('#group_profile').wizard('previous');
});
</script>